import type {
  ArmType, BackType, BodyType, EarType, EyeType, HeadType, HornType, LegType,
  MouthType, MythologyId, SkinType, TailType, WingType,
} from "./types";

type W<T extends string> = Partial<Record<T, number>>;

export interface Archetype {
  name: string;
  /** predicates over a loose anatomy record; count matches */
  match: Partial<{
    body: BodyType[]; head: HeadType[]; eyesCount: number[]; mouth: MouthType[]; eyes: EyeType[]; ears: EarType[];
    horns: HornType[]; legs: LegType[]; wings: WingType[]; tail: TailType[]; arms: ArmType[];
    armCount: number[]; skin: SkinType[]; back: BackType[];
  }>;
  need: number;
}

export interface MythologyFamily {
  id: MythologyId;
  label: string;
  short: string;
  body: W<BodyType>;
  head: W<HeadType>;
  eyes: W<EyeType>;
  mouth: W<MouthType>;
  horns: W<HornType>;
  ears: W<EarType>;
  arms: W<ArmType>;
  legs: W<LegType>;
  wings: W<WingType>;
  tail: W<TailType>;
  back: W<BackType>;
  skin: W<SkinType>;
  hues: number[]; // preferred body hue centers (0-360)
  onsets: string[];
  nuclei: string[];
  codas: string[];
  epithets: string[]; // "The ___ One" / "___ of the ___"
  domains: string[];
  classAdj: string[];
  classNoun: string[];
  habitats: string[];
  omens: string[];
  traits: string[];
  archetypes: Archetype[];
}

export const MYTHOLOGIES: Record<MythologyId, MythologyFamily> = {
  greek: {
    id: "greek", label: "Greek & Roman Myth", short: "GREEK",
    body: { barrel: 3, tall: 2, quadruped: 3, serpent: 2, hunched: 1, blob: 1 },
    head: { cube: 2, sphere: 2, skull: 1, snout: 3, beak: 1, wide: 1, tall: 1 },
    eyes: { round: 3, hollow: 1, glow: 1, slit: 1, ring: 1 },
    mouth: { grin: 2, fangs: 2, maw: 1, tusks: 1, flat: 2, beak: 1 },
    horns: { none: 3, curved: 3, ram: 2, straight: 1, single: 1 },
    ears: { none: 2, pointed: 2, round: 2 },
    arms: { stubby: 2, long: 2, claw: 2, none: 1 },
    legs: { hoof: 3, thick: 2, long: 1, bird: 1, none: 1 },
    wings: { none: 4, feather: 3, bat: 1 },
    tail: { none: 2, serpent: 2, thin: 2, fish: 1, thick: 1 },
    back: { none: 4, mane: 1, spikes: 1 },
    skin: { smooth: 3, fur: 2, scales: 2, stone: 1 },
    hues: [30, 200, 350, 45],
    onsets: ["kar", "ekh", "lam", "sk", "tyr", "ory", "kh", "peth", "ger", "dra", "hy", "ste"],
    nuclei: ["a", "e", "o", "y", "io", "ei"],
    codas: ["os", "on", "eus", "ax", "ion", "yx", "ra", "ne", "is", "or"],
    epithets: ["Bronze-Hoofed", "Stone-Gazing", "Hundred-Handed", "Labyrinth-Born", "Wine-Dark", "Oracle-Eyed", "Tide-Wrought", "Thunder-Marked"],
    domains: ["the Labyrinth", "the Wine-Dark Sea", "the Bronze Gate", "the Sunken Isle", "the Olive Grove", "the Oracle's Cave"],
    classAdj: ["ABYSSAL", "BRONZE", "LABYRINTH", "TIDE", "MARBLE", "STONE-GAZE"],
    classNoun: ["CHIMERA", "HYDRA-KIN", "STALKER", "GORGONID", "BEAST", "HERALD"],
    habitats: ["in the bones of a drowned temple", "beneath an olive grove that never fruits", "at the center of a maze no one built", "along cliffs where ships go quiet"],
    omens: ["shortly before the sea turns black", "when a statue is found weeping salt", "whenever a bronze bell rings underwater", "the night after a hero boasts"],
    traits: ["STONE-GAZE", "TIDE-BORN", "LABYRINTHINE", "OATH-BOUND", "MANY-HEADED"],
    archetypes: [
      { name: "MINOTAUR", match: { head: ["snout"], horns: ["curved", "ram"], legs: ["hoof", "thick"], body: ["barrel", "tall"] }, need: 4 },
      { name: "GORGON", match: { body: ["serpent"], tail: ["serpent"], back: ["mane"], eyes: ["glow", "ring"], head: ["sphere", "cube"] }, need: 3 },
      { name: "CYCLOPS", match: { eyesCount: [1], body: ["barrel", "tall"], legs: ["thick", "stubby"] }, need: 3 },
      { name: "HARPY", match: { wings: ["feather"], legs: ["bird"], head: ["beak", "sphere"] }, need: 3 },
      { name: "CENTAUR-KIN", match: { body: ["quadruped"], legs: ["hoof"], arms: ["long", "stubby"] }, need: 3 },
    ],
  },
  norse: {
    id: "norse", label: "Norse & Germanic Lore", short: "NORSE",
    body: { tall: 3, barrel: 3, hunched: 2, serpent: 2, quadruped: 1 },
    head: { cube: 3, skull: 3, snout: 2, wide: 1, tall: 1 },
    eyes: { hollow: 3, round: 2, glow: 2, slit: 1 },
    mouth: { fangs: 3, grin: 2, flat: 2, maw: 1, tusks: 1 },
    horns: { none: 3, curved: 2, antlers: 2, straight: 2, ram: 1 },
    ears: { none: 3, pointed: 2, round: 1 },
    arms: { long: 3, stubby: 2, claw: 2, blade: 1 },
    legs: { thick: 3, stubby: 2, long: 1, none: 1 },
    wings: { none: 6, feather: 1 },
    tail: { none: 3, serpent: 2, thick: 1, thin: 1 },
    back: { none: 3, spikes: 1, mane: 2, fins: 1 },
    skin: { fur: 3, bone: 2, stone: 2, smooth: 1, scales: 1 },
    hues: [210, 190, 20, 100],
    onsets: ["gr", "skj", "hr", "vál", "fen", "thr", "jor", "ulf", "sv", "bra", "nid", "hel"],
    nuclei: ["a", "ó", "u", "i", "ei", "au"],
    codas: ["nir", "gr", "ulf", "mund", "rik", "hag", "vald", "th", "gar", "n"],
    epithets: ["Frost-Jawed", "Barrow-Waking", "Root-Gnawing", "Wolf-Fed", "Iron-Bearded", "Grave-Cold", "Ash-Crowned", "World-Coiling"],
    domains: ["the Barrow Mound", "the Frost Fjord", "the Iron Wood", "the World-Root", "the Ninth Hall", "the Drowned Longship"],
    classAdj: ["FROST", "BARROW", "IRON-WOOD", "ASHEN", "GRAVE", "WOLF-FED"],
    classNoun: ["DRAUGR-KIN", "WYRM", "TROLL", "STALKER", "WIGHT", "FIEND"],
    habitats: ["inside a barrow that was sealed twice", "below the roots of a tree older than iron", "where the fjord ice groans at night", "in a longhouse burned and rebuilt nine times"],
    omens: ["before a winter that lasts three years", "when ravens fly backwards", "the night the ice sings", "after an oath is broken at a feast"],
    traits: ["FROST-VEINED", "BARROW-BOUND", "OATH-EATER", "IRON-SKINNED", "WINTER-HERALD"],
    archetypes: [
      { name: "DRAUGR", match: { skin: ["bone", "stone"], eyes: ["hollow", "glow"], head: ["skull", "cube"], body: ["tall", "hunched"] }, need: 3 },
      { name: "TROLL", match: { body: ["barrel", "hunched"], arms: ["long"], skin: ["stone", "fur"], mouth: ["tusks", "fangs"] }, need: 3 },
      { name: "WORLD-SERPENT", match: { body: ["serpent"], tail: ["serpent"], mouth: ["fangs", "maw"] }, need: 3 },
      { name: "FENRIR-KIN", match: { body: ["quadruped"], head: ["snout"], mouth: ["fangs", "maw"], skin: ["fur"] }, need: 4 },
    ],
  },
  egyptian: {
    id: "egyptian", label: "Egyptian Myth", short: "EGYPTIAN",
    body: { tall: 4, quadruped: 3, barrel: 1, serpent: 2, floating: 1 },
    head: { snout: 3, beak: 3, jar: 2, tall: 2, cube: 1 },
    eyes: { ring: 3, round: 2, glow: 2, slit: 1 },
    mouth: { flat: 3, beak: 2, fangs: 1, maw: 1, grin: 1 },
    horns: { none: 4, curved: 2, straight: 1, single: 1, crown: 2 },
    ears: { pointed: 3, long: 2, none: 2 },
    arms: { long: 3, stubby: 2, none: 1, claw: 1 },
    legs: { long: 3, thick: 2, bird: 1, none: 1 },
    wings: { none: 4, feather: 3 },
    tail: { thin: 3, none: 2, serpent: 1, fan: 1 },
    back: { none: 5, fins: 1 },
    skin: { smooth: 4, scales: 1, stone: 2 },
    hues: [40, 200, 20, 50],
    onsets: ["am", "seb", "kh", "nef", "an", "ap", "sek", "wad", "hep", "meh", "sob", "ba"],
    nuclei: ["a", "e", "u", "o", "ae"],
    codas: ["tet", "khet", "mut", "ris", "nub", "ket", "fer", "ep", "os", "ur"],
    epithets: ["Jackal-Eared", "Reed-Silent", "Sand-Buried", "Scarab-Hearted", "Sun-Bleached", "Tomb-Sealed", "Nile-Drinking", "Ibis-Still"],
    domains: ["the Reed Marsh", "the Sealed Tomb", "the Red Desert", "the West Bank", "the Weighing Hall", "the Dry River"],
    classAdj: ["SAND", "TOMB", "REED", "SUN-BLEACHED", "JACKAL", "SCARAB"],
    classNoun: ["WATCHER", "DEVOURER", "SPHINX-KIN", "SENTINEL", "HERALD", "SPIRIT"],
    habitats: ["beneath a tomb whose door was painted shut", "in the reeds where the river forgets its name", "on the west bank, facing the setting sun", "in a canopic jar that rattles"],
    omens: ["when the river fails to flood", "before a name is scratched from a wall", "whenever a scarab walks backwards", "the day a shadow falls the wrong way"],
    traits: ["TOMB-SEALED", "SUN-BLEACHED", "HEART-WEIGHER", "REED-SILENT", "SAND-WALKER"],
    archetypes: [
      { name: "SPHINX-KIN", match: { body: ["quadruped"], head: ["cube", "sphere", "jar"], wings: ["feather", "none"], legs: ["thick", "long"] }, need: 3 },
      { name: "AMMIT-KIN", match: { head: ["snout"], mouth: ["maw", "fangs"], body: ["quadruped", "barrel"], skin: ["scales"] }, need: 3 },
      { name: "SERPOPARD", match: { body: ["quadruped"], tail: ["serpent"], head: ["snout"] }, need: 3 },
    ],
  },
  japanese: {
    id: "japanese", label: "Japanese Yōkai", short: "YŌKAI",
    body: { blob: 3, floating: 3, hunched: 2, tall: 2, barrel: 1, shell: 2 },
    head: { sphere: 3, wide: 2, cube: 2, beak: 2, jar: 2, flame: 1 },
    eyes: { round: 3, glow: 2, slit: 2, hollow: 1, cross: 1 },
    mouth: { grin: 4, tongue: 2, beak: 1, fangs: 2, none: 1, maw: 1 },
    horns: { none: 3, oni: 4, single: 2, straight: 1 },
    ears: { none: 2, pointed: 3, long: 1, round: 1 },
    arms: { long: 3, stubby: 3, none: 2, claw: 1 },
    legs: { stubby: 3, none: 3, long: 1, bird: 1, thick: 1 },
    wings: { none: 5, feather: 2 },
    tail: { none: 3, fan: 2, thick: 1, thin: 1, fish: 1 },
    back: { none: 4, shell: 2, spikes: 1 },
    skin: { smooth: 4, fur: 2, scales: 1 },
    hues: [355, 260, 120, 30],
    onsets: ["kur", "shi", "on", "yam", "tsu", "nur", "kap", "gash", "ubu", "ten", "rok", "hō"],
    nuclei: ["a", "o", "u", "i", "ō", "ei"],
    codas: ["ki", "me", "ro", "gu", "ba", "shi", "ta", "n", "ne", "do"],
    epithets: ["Long-Necked", "Paper-Lantern", "Hundred-Grinned", "Mountain-Nosed", "Bathhouse-Lurking", "Umbrella-Footed", "Moon-Viewing", "Tongue-Lolling"],
    domains: ["the Mountain Pass", "the Paper Lantern", "the Old Bathhouse", "the Cedar Shrine", "the Hundred Tales", "the Riverbank"],
    classAdj: ["HOLLOW", "MOUNTAIN", "LANTERN", "RIVER", "SHRINE", "NIGHT-PARADE"],
    classNoun: ["YŌKAI", "ONI", "SPIRIT", "TRICKSTER", "DEMON", "GRINNER"],
    habitats: ["behind a shrine gate that faces the wrong way", "in a bathhouse abandoned mid-season", "at the top of a mountain pass no map agrees on", "inside a lantern that lights itself"],
    omens: ["on the hundredth telling of a ghost story", "when cedar branches snap on a windless night", "before a festival is cancelled", "whenever a child counts to nine twice"],
    traits: ["SHAPESHIFTER", "ILLUSORY", "MOUNTAIN-BOUND", "TRICKSTER", "NIGHT-PARADER"],
    archetypes: [
      { name: "ONI", match: { horns: ["oni", "straight"], mouth: ["fangs", "tusks", "grin"], body: ["barrel", "tall", "hunched"], arms: ["long", "claw"] }, need: 3 },
      { name: "TENGU", match: { head: ["beak"], wings: ["feather"], legs: ["long", "bird"] }, need: 3 },
      { name: "KAPPA", match: { back: ["shell"], body: ["shell", "blob"], head: ["wide", "sphere"], legs: ["stubby"] }, need: 3 },
      { name: "HITOTSUME", match: { eyesCount: [1], mouth: ["grin", "tongue"], body: ["blob", "hunched"] }, need: 3 },
    ],
  },
  chinese: {
    id: "chinese", label: "Chinese Folklore", short: "CHINESE",
    body: { serpent: 4, quadruped: 3, tall: 1, floating: 2, barrel: 1 },
    head: { snout: 3, sphere: 2, cube: 1, wide: 2, tall: 1, skull: 1 },
    eyes: { round: 3, glow: 2, slit: 2, ring: 1 },
    mouth: { fangs: 3, grin: 2, maw: 2, flat: 1, tusks: 1 },
    horns: { none: 2, antlers: 4, straight: 2, curved: 1, single: 1 },
    ears: { pointed: 2, fin: 3, round: 1, none: 1 },
    arms: { stubby: 3, claw: 3, none: 2 },
    legs: { stubby: 3, none: 3, bird: 1, thick: 1, hoof: 1 },
    wings: { none: 6, feather: 1 },
    tail: { serpent: 3, fish: 2, thick: 2, fan: 1 },
    back: { mane: 3, fins: 3, spikes: 2, none: 1 },
    skin: { scales: 5, fur: 2, smooth: 1 },
    hues: [0, 40, 140, 200],
    onsets: ["long", "qi", "bai", "xiang", "hun", "tao", "zhu", "feng", "nian", "gui", "yao", "jiu"],
    nuclei: ["a", "i", "u", "ao", "ei", "ou"],
    codas: ["long", "ze", "wei", "ling", "tian", "hu", "ming", "gu", "ren", "jing"],
    epithets: ["Pearl-Chasing", "Nine-Tailed", "Cloud-Coiling", "Jade-Scaled", "Firecracker-Fearing", "Well-Dwelling", "Thunder-Whiskered", "Peach-Guarding"],
    domains: ["the Jade Well", "the Cloud Sea", "the Peach Orchard", "the Yellow River", "the Nine Gates", "the Lantern Street"],
    classAdj: ["JADE", "CLOUD", "RIVER", "NINE-TAILED", "THUNDER", "PEARL"],
    classNoun: ["DRAGON-KIN", "SPIRIT", "GUARDIAN", "BEAST", "FOX-KIN", "DEVOURER"],
    habitats: ["coiled at the bottom of a jade-green well", "in the cloud sea above a mountain painted a thousand times", "beneath a bridge where coins are thrown for luck", "inside a lantern district after the last shop closes"],
    omens: ["before the river changes course", "when firecrackers fail to light", "on the first night of a new year without a moon", "whenever a pearl is found in fresh water"],
    traits: ["CLOUD-WALKER", "PEARL-HOARDER", "RIVER-DWELLER", "THUNDER-BORN", "NINE-LIVED"],
    archetypes: [
      { name: "LÓNG-KIN", match: { body: ["serpent"], horns: ["antlers"], back: ["mane", "fins"], skin: ["scales"], arms: ["claw", "stubby"] }, need: 4 },
      { name: "NIAN", match: { body: ["quadruped"], head: ["snout", "wide"], mouth: ["maw", "fangs"], back: ["mane"] }, need: 3 },
      { name: "HULI JING", match: { tail: ["fan", "thick"], head: ["snout"], skin: ["fur"], body: ["quadruped", "tall"] }, need: 3 },
    ],
  },
  filipino: {
    id: "filipino", label: "Filipino Folklore", short: "FILIPINO",
    body: { tall: 4, hunched: 2, floating: 2, serpent: 2, quadruped: 2, blob: 1 },
    head: { snout: 3, sphere: 2, skull: 2, wide: 2, cube: 1, tall: 1 },
    eyes: { glow: 3, round: 2, hollow: 2, slit: 1 },
    mouth: { fangs: 3, grin: 3, tongue: 2, maw: 2, flat: 1 },
    horns: { none: 4, straight: 1, curved: 1, single: 1 },
    ears: { long: 3, pointed: 3, round: 1, none: 1 },
    arms: { long: 4, claw: 2, stubby: 2, none: 1 },
    legs: { long: 4, hoof: 3, stubby: 1, none: 2, thick: 1 },
    wings: { none: 4, bat: 3, stub: 1 },
    tail: { none: 3, thin: 2, thick: 1, serpent: 2 },
    back: { none: 4, mane: 2, spikes: 1 },
    skin: { smooth: 3, fur: 3, scales: 1, bone: 1 },
    hues: [25, 280, 120, 200],
    onsets: ["bak", "tik", "man", "sig", "bun", "mar", "dal", "kap", "tiy", "asw", "ag", "bal"],
    nuclei: ["a", "u", "i", "o", "aw", "ay"],
    codas: ["nawa", "lang", "gal", "bin", "gis", "ta", "kaw", "lay", "ngal", "tan"],
    epithets: ["Backwards-Hoofed", "Half-Bodied", "Moon-Swallowing", "Balete-Rooted", "Salt-Fearing", "Long-Tongued", "Giggling", "Rice-Field-Walking"],
    domains: ["the Balete Tree", "the Rice Terrace", "the Seven Moons", "the Swamp Road", "the Salt Coast", "the Night Market"],
    classAdj: ["HOLLOW", "MOON", "BALETE", "MARSH", "SALT", "MIDNIGHT"],
    classNoun: ["TIKBALANG-KIN", "FIEND", "WATCHER", "STALKER", "MOON-EATER", "SPIRIT"],
    habitats: ["inside a balete tree that grew around a road", "at the edge of rice terraces after the last lamp is out", "along a swamp road that gets longer at night", "under a house on stilts, breathing quietly"],
    omens: ["shortly before violent storms cross the islands", "when the moon looks half-eaten", "whenever a traveler's shirt is turned inside out", "the night a dog barks at nothing three times"],
    traits: ["SHAPESHIFTER", "MOON-EATER", "SALT-FEARING", "ROAD-TWISTER", "BALETE-BOUND"],
    archetypes: [
      { name: "TIKBALANG", match: { head: ["snout"], legs: ["hoof", "long"], body: ["tall"], arms: ["long"], back: ["mane"] }, need: 4 },
      { name: "MANANANGGAL", match: { wings: ["bat"], legs: ["none"], body: ["floating", "tall"], mouth: ["fangs", "tongue"] }, need: 3 },
      { name: "BAKUNAWA", match: { body: ["serpent"], mouth: ["maw", "fangs"], back: ["fins", "spikes"], tail: ["serpent", "fish"] }, need: 3 },
      { name: "SIGBIN", match: { body: ["quadruped"], ears: ["long"], tail: ["thin", "thick"], legs: ["long", "stubby"] }, need: 3 },
      { name: "BUNGISNGIS", match: { eyesCount: [1], mouth: ["grin", "tusks"], body: ["barrel", "hunched"] }, need: 3 },
    ],
  },
  celtic: {
    id: "celtic", label: "Celtic Folklore", short: "CELTIC",
    body: { tall: 3, floating: 3, quadruped: 2, hunched: 2, blob: 1 },
    head: { sphere: 2, tall: 3, skull: 2, snout: 2, wide: 1 },
    eyes: { hollow: 3, round: 2, glow: 2, ring: 1 },
    mouth: { none: 2, flat: 2, maw: 2, grin: 1, fangs: 1 },
    horns: { none: 4, antlers: 4, curved: 1 },
    ears: { pointed: 4, none: 2, long: 1 },
    arms: { long: 3, stubby: 1, none: 2, tentacle: 1 },
    legs: { long: 2, hoof: 3, none: 3, stubby: 1 },
    wings: { none: 6, stub: 1 },
    tail: { none: 4, fish: 2, thin: 1 },
    back: { none: 4, mane: 2 },
    skin: { smooth: 3, fur: 2, stone: 1, bone: 1 },
    hues: [130, 100, 210, 40],
    onsets: ["bran", "mor", "cail", "dul", "sel", "bal", "fear", "aoi", "cú", "each", "gwyn", "tar"],
    nuclei: ["a", "e", "i", "o", "ea", "ai"],
    codas: ["leach", "rig", "an", "wen", "kie", "gh", "ros", "ain", "ath", "dwr"],
    epithets: ["Wailing", "Bog-Drowned", "Antler-Crowned", "Hollow-Hill", "Kelp-Maned", "Thrice-Knocking", "Mist-Walking", "Barrow-Singing"],
    domains: ["the Hollow Hill", "the Black Bog", "the Standing Stones", "the Grey Loch", "the Hawthorn Ring", "the Mist Road"],
    classAdj: ["BOG", "HOLLOW-HILL", "MIST", "LOCH", "HAWTHORN", "WAILING"],
    classNoun: ["WRAITH", "FAE-KIN", "HOUND", "BANSHEE-KIN", "SPIRIT", "KELPIE-KIN"],
    habitats: ["beneath a hollow hill that hums on certain nights", "in a bog that returns things older than it should", "beside a loch that reflects the wrong sky", "in a ring of hawthorn no farmer will cut"],
    omens: ["three nights before a death in the house", "when the mist arrives against the wind", "whenever a stone circle gains a stone", "on the morning the milk turns"],
    traits: ["OMEN-BEARER", "MIST-WALKER", "BOG-BOUND", "FAE-TOUCHED", "KEENING"],
    archetypes: [
      { name: "BANSHEE", match: { body: ["floating", "tall"], legs: ["none"], mouth: ["maw", "none"], eyes: ["hollow"] }, need: 3 },
      { name: "KELPIE", match: { body: ["quadruped"], head: ["snout"], legs: ["hoof"], tail: ["fish"], back: ["mane"] }, need: 3 },
      { name: "CERNUNNOS-KIN", match: { horns: ["antlers"], body: ["tall"], legs: ["hoof"] }, need: 3 },
      { name: "CÙ SÌTH", match: { body: ["quadruped"], head: ["snout"], skin: ["fur"], mouth: ["fangs"] }, need: 4 },
    ],
  },
  slavic: {
    id: "slavic", label: "Slavic Folklore", short: "SLAVIC",
    body: { hunched: 4, tall: 2, blob: 2, quadruped: 1, barrel: 2 },
    head: { skull: 2, cube: 3, tall: 2, sphere: 2, beak: 1 },
    eyes: { hollow: 2, glow: 3, round: 2, slit: 1 },
    mouth: { fangs: 3, grin: 2, flat: 2, tusks: 1, maw: 1 },
    horns: { none: 5, straight: 1, curved: 1, antlers: 1 },
    ears: { pointed: 2, long: 2, round: 2, none: 1 },
    arms: { long: 4, stubby: 2, claw: 2 },
    legs: { bird: 3, long: 2, stubby: 2, thick: 1 },
    wings: { none: 5, feather: 1, bat: 1 },
    tail: { none: 4, thin: 2, thick: 1 },
    back: { none: 4, mane: 1, spikes: 1 },
    skin: { fur: 3, smooth: 2, bone: 2, stone: 1 },
    hues: [30, 15, 200, 90],
    onsets: ["bab", "kosch", "vod", "lesh", "rus", "zmey", "dom", "stri", "mor", "vil", "chu", "bol"],
    nuclei: ["a", "e", "o", "i", "ya", "yo"],
    codas: ["nik", "yaga", "chey", "ov", "alka", "goy", "voi", "ska", "yen", "dor"],
    epithets: ["Chicken-Legged", "Deathless", "Birch-Skinned", "Stove-Dwelling", "Needle-Hearted", "Frost-Whiskered", "Field-Walking", "Rusalka-Wet"],
    domains: ["the Birch Forest", "the Black Stove", "the Frozen Lake", "the Thirteenth Hut", "the Wheat Field", "the Crossroads"],
    classAdj: ["BIRCH", "STOVE", "DEATHLESS", "FROST", "FIELD", "CROSSROADS"],
    classNoun: ["FIEND", "HAG-KIN", "SPIRIT", "LESHY-KIN", "HOUSEHOLD-THING", "WIGHT"],
    habitats: ["in a hut that turns to face whoever calls it", "behind a stove in a house nobody remembers building", "at the bottom of a lake that freezes from below", "in birch forests where the paths rearrange"],
    omens: ["when bread is left unsalted", "the night the stove goes cold on its own", "before a wedding is called off", "whenever a needle is found in an egg"],
    traits: ["DEATHLESS", "HOUSE-BOUND", "FOREST-WALKER", "TRICKSTER", "CURSE-BEARER"],
    archetypes: [
      { name: "BABA-KIN", match: { legs: ["bird"], body: ["hunched"], head: ["tall", "skull"], arms: ["long"] }, need: 3 },
      { name: "LESHY", match: { body: ["tall"], horns: ["antlers"], skin: ["fur", "stone"], eyes: ["glow"] }, need: 3 },
      { name: "ZMEY", match: { body: ["serpent"], wings: ["bat"], mouth: ["fangs", "maw"] }, need: 3 },
      { name: "DOMOVOI", match: { body: ["blob", "hunched"], skin: ["fur"], legs: ["stubby"], arms: ["stubby"] }, need: 4 },
    ],
  },
  hindu: {
    id: "hindu", label: "Hindu Folklore", short: "HINDU",
    body: { tall: 3, serpent: 3, barrel: 2, floating: 1, quadruped: 1 },
    head: { sphere: 2, cube: 2, snout: 2, wide: 2, tall: 1, skull: 1 },
    eyes: { round: 3, glow: 2, ring: 2, slit: 1 },
    mouth: { fangs: 3, tusks: 3, grin: 2, maw: 1, flat: 1 },
    horns: { none: 4, crown: 3, curved: 1, single: 1 },
    ears: { long: 2, round: 2, pointed: 2, fin: 1 },
    arms: { long: 4, claw: 3, stubby: 1 },
    legs: { long: 2, thick: 2, none: 2, hoof: 1, stubby: 1 },
    wings: { none: 5, feather: 2 },
    tail: { serpent: 3, none: 2, thin: 2, fan: 1 },
    back: { none: 3, fins: 2, mane: 1, spikes: 1 },
    skin: { smooth: 3, scales: 3, fur: 1 },
    hues: [220, 20, 40, 300],
    onsets: ["rak", "nag", "vet", "ash", "pish", "gar", "mak", "yak", "bhu", "kum", "vish", "dan"],
    nuclei: ["a", "i", "u", "ā", "ai", "au"],
    codas: ["sha", "ra", "ala", "ura", "aka", "ini", "asa", "van", "dha", "ta"],
    epithets: ["Many-Armed", "Hooded", "Ash-Smeared", "Thousand-Fanged", "Monsoon-Born", "Ghat-Haunting", "Upside-Hanging", "Cobra-Crowned"],
    domains: ["the Cremation Ghat", "the Monsoon River", "the Banyan Root", "the Serpent Well", "the Burning Ground", "the Salt Flats"],
    classAdj: ["MONSOON", "SERPENT-BORN", "ASH", "BANYAN", "GHAT", "THOUSAND-FANGED"],
    classNoun: ["RAKSHASA-KIN", "NAGA-KIN", "DEVOURER", "SPIRIT", "GUARDIAN", "WRAITH"],
    habitats: ["hanging upside down from a banyan older than the village", "in a well where cobras go to sleep", "at the cremation ghats between the last fire and dawn", "beneath the monsoon river when it runs backward"],
    omens: ["the night before the monsoon breaks", "when a cobra is seen with two heads", "whenever incense smoke falls instead of rises", "before a temple bell rings on its own"],
    traits: ["SHAPESHIFTER", "MANY-ARMED", "SERPENT-BLOODED", "ASH-EATER", "MONSOON-HERALD"],
    archetypes: [
      { name: "NAGA", match: { body: ["serpent"], tail: ["serpent"], horns: ["crown"], skin: ["scales"], arms: ["long", "claw"] }, need: 3 },
      { name: "RAKSHASA", match: { mouth: ["tusks", "fangs"], armCount: [4, 6], horns: ["crown", "none"], body: ["tall", "barrel"] }, need: 3 },
      { name: "VETALA", match: { body: ["floating", "tall"], legs: ["none"], skin: ["bone", "smooth"], mouth: ["fangs"] }, need: 3 },
      { name: "MAKARA", match: { body: ["quadruped", "serpent"], head: ["snout"], tail: ["fish"], skin: ["scales"] }, need: 3 },
    ],
  },
  mesopotamian: {
    id: "mesopotamian", label: "Mesopotamian Myth", short: "MESOPOTAMIAN",
    body: { quadruped: 4, tall: 3, barrel: 2, serpent: 2 },
    head: { cube: 3, snout: 2, beak: 2, tall: 2, skull: 1 },
    eyes: { round: 3, ring: 2, glow: 2, hollow: 1 },
    mouth: { flat: 3, fangs: 2, maw: 1, grin: 1, beak: 1 },
    horns: { none: 2, straight: 3, curved: 2, crown: 2 },
    ears: { none: 2, round: 2, pointed: 2 },
    arms: { long: 2, claw: 2, none: 3, stubby: 1 },
    legs: { hoof: 3, thick: 3, bird: 2, long: 1 },
    wings: { feather: 4, none: 3 },
    tail: { thin: 2, thick: 2, serpent: 1, none: 1, fan: 1 },
    back: { none: 3, mane: 2, fins: 1 },
    skin: { stone: 3, scales: 2, fur: 2, smooth: 1 },
    hues: [35, 45, 200, 15],
    onsets: ["lam", "pazu", "hum", "tia", "ugal", "mush", "kus", "ash", "nam", "gal", "ur", "zu"],
    nuclei: ["a", "u", "i", "e", "ua"],
    codas: ["assu", "zu", "baba", "mat", "lu", "shu", "gal", "tar", "kur", "nun"],
    epithets: ["Wind-Bringing", "Gate-Guarding", "Clay-Born", "Cedar-Guarding", "Fever-Breathing", "Seven-Headed", "Brick-Skinned", "Flood-Old"],
    domains: ["the Cedar Forest", "the Ziggurat Steps", "the Bitter River", "the Clay Tablet", "the Gate of Seven", "the Salt Marsh"],
    classAdj: ["CLAY", "GATE", "CEDAR", "FEVER-WIND", "ZIGGURAT", "FLOOD"],
    classNoun: ["LAMASSU-KIN", "GUARDIAN", "DEMON", "WATCHER", "HERALD", "BEAST"],
    habitats: ["between the paws of a statue that was never finished", "at the top of ziggurat steps worn to a ramp", "in cedar forests that the kings forgot to cut", "under a clay tablet listing names that were never born"],
    omens: ["before the fever wind arrives from the west", "when the river tastes bitter", "whenever a brick is found with two stamps", "the night a gate opens toward the desert"],
    traits: ["GATE-KEEPER", "FEVER-WIND", "CLAY-BORN", "FLOOD-OLD", "TERRITORIAL"],
    archetypes: [
      { name: "LAMASSU-KIN", match: { body: ["quadruped"], wings: ["feather"], head: ["cube", "tall"], legs: ["hoof", "thick"] }, need: 3 },
      { name: "PAZUZU-KIN", match: { wings: ["feather", "bat"], head: ["snout", "skull"], legs: ["bird"], tail: ["serpent", "thin"] }, need: 3 },
      { name: "MUŠḪUŠŠU", match: { body: ["quadruped", "serpent"], horns: ["straight", "crown"], skin: ["scales"], legs: ["bird"] }, need: 3 },
    ],
  },
  persian: {
    id: "persian", label: "Persian & Middle Eastern Lore", short: "PERSIAN",
    body: { tall: 3, floating: 3, quadruped: 2, barrel: 1, serpent: 1 },
    head: { flame: 3, sphere: 2, beak: 2, snout: 2, cube: 1, tall: 1 },
    eyes: { glow: 4, round: 2, slit: 2, ring: 1 },
    mouth: { fangs: 2, grin: 2, flat: 2, beak: 1, maw: 1, none: 1 },
    horns: { none: 4, curved: 2, straight: 1, crown: 1 },
    ears: { pointed: 3, none: 2, long: 1, round: 1 },
    arms: { long: 3, claw: 2, none: 2, stubby: 1 },
    legs: { none: 3, long: 2, hoof: 2, bird: 1 },
    wings: { none: 3, feather: 3, bat: 1 },
    tail: { none: 2, thin: 2, fan: 2, serpent: 1 },
    back: { none: 4, mane: 1, spikes: 1 },
    skin: { smooth: 4, fur: 1, scales: 1, stone: 1 },
    hues: [25, 180, 45, 270],
    onsets: ["az", "dēv", "sim", "kar", "mān", "zah", "rukh", "pēr", "ahr", "gul", "shah", "nas"],
    nuclei: ["a", "ā", "i", "u", "ē", "ai"],
    codas: ["dahak", "urgh", "ish", "kadan", "zan", "rish", "mar", "van", "gar", "ud"],
    epithets: ["Smokeless", "Three-Headed", "Dog-Headed", "Sandstorm-Walking", "Lamp-Bound", "Rose-Scented", "Mountain-Nesting", "Salt-Tongued"],
    domains: ["the Salt Desert", "the Mountain Nest", "the Rose Garden", "the Bottomless Lamp", "the Seven Cities", "the Bazaar at Dusk"],
    classAdj: ["SMOKELESS", "SANDSTORM", "LAMP", "ROSE", "DUSK", "MOUNTAIN-NEST"],
    classNoun: ["DIV", "ROC-KIN", "DJINN-KIN", "FIEND", "WATCHER", "HERALD"],
    habitats: ["in a lamp that no one dares polish", "on a mountain nest built from ship masts", "in a rose garden that blooms only at night", "in the bazaar after the last lantern is snuffed"],
    omens: ["before a sandstorm arrives at noon", "whenever a shadow smells of smoke", "when a caravan arrives with one extra camel", "the night the wind carries rose scent uphill"],
    traits: ["SMOKELESS", "WISH-TWISTER", "SANDSTORM-HERALD", "ILLUSORY", "MOUNTAIN-NESTER"],
    archetypes: [
      { name: "DIV", match: { horns: ["curved", "straight"], mouth: ["fangs", "tusks"], skin: ["fur", "stone"], body: ["tall", "barrel"] }, need: 3 },
      { name: "ROC-KIN", match: { wings: ["feather"], head: ["beak"], legs: ["bird"], body: ["barrel", "floating"] }, need: 3 },
      { name: "DJINN-KIN", match: { body: ["floating"], legs: ["none"], head: ["flame"], eyes: ["glow"] }, need: 3 },
    ],
  },
  mesoamerican: {
    id: "mesoamerican", label: "Mesoamerican Myth", short: "MESOAMERICAN",
    body: { serpent: 4, quadruped: 2, tall: 2, blob: 1, hunched: 1 },
    head: { snout: 3, skull: 3, wide: 2, cube: 2, beak: 1 },
    eyes: { round: 3, ring: 2, hollow: 2, glow: 1 },
    mouth: { fangs: 3, maw: 3, grin: 1, flat: 1, tongue: 1 },
    horns: { none: 4, crown: 3, straight: 1 },
    ears: { none: 2, round: 2, fin: 2, pointed: 1 },
    arms: { claw: 3, stubby: 2, none: 2, long: 1 },
    legs: { none: 3, thick: 2, stubby: 2, long: 1 },
    wings: { feather: 3, none: 3, bat: 1 },
    tail: { serpent: 3, thick: 1, fan: 2, none: 1 },
    back: { fins: 2, mane: 2, spikes: 2, none: 2 },
    skin: { scales: 3, bone: 2, smooth: 2, stone: 1 },
    hues: [150, 30, 350, 60],
    onsets: ["ahui", "tzitz", "xol", "cip", "nag", "kuk", "mict", "tlal", "cam", "itz", "chac", "way"],
    nuclei: ["a", "o", "i", "e", "ua", "ui"],
    codas: ["tli", "tl", "mitl", "coatl", "lan", "otl", "ec", "tec", "chan", "xin"],
    epithets: ["Feather-Scaled", "Obsidian-Toothed", "Star-Skeletal", "Cenote-Deep", "Jaguar-Spotted", "Smoke-Mirrored", "Cacao-Dark", "Skull-Racked"],
    domains: ["the Cenote", "the Obsidian Mirror", "the Ball Court", "the Ninth Underworld", "the Jaguar Temple", "the Maize Field"],
    classAdj: ["OBSIDIAN", "CENOTE", "FEATHERED", "JAGUAR", "SMOKE-MIRROR", "STAR-BONE"],
    classNoun: ["SERPENT", "DEVOURER", "SKELETAL-KIN", "SPIRIT", "HERALD", "BEAST"],
    habitats: ["at the bottom of a cenote where the light bends", "in a ball court that echoes when empty", "on a skull rack that counts itself at night", "in a maize field that ripens on the wrong month"],
    omens: ["when the obsidian mirror shows a second face", "before an eclipse the priests did not predict", "whenever a jaguar is heard but not seen", "the night the cenote water rises"],
    traits: ["STAR-BONED", "CENOTE-DWELLER", "OBSIDIAN-TOOTHED", "UNDERWORLD-BOUND", "OMEN-BEARER"],
    archetypes: [
      { name: "FEATHERED SERPENT", match: { body: ["serpent"], wings: ["feather"], back: ["mane", "fins"], skin: ["scales"] }, need: 3 },
      { name: "TZITZIMITL", match: { skin: ["bone"], head: ["skull"], body: ["tall", "floating"], eyes: ["hollow", "ring"] }, need: 3 },
      { name: "AHUIZOTL", match: { body: ["quadruped"], tail: ["thick", "serpent"], head: ["snout"], arms: ["claw"] }, need: 3 },
      { name: "CIPACTLI", match: { body: ["serpent", "quadruped"], mouth: ["maw"], back: ["spikes"], skin: ["scales"] }, need: 4 },
    ],
  },
  african: {
    id: "african", label: "African Folklore Traditions", short: "AFRICAN",
    body: { quadruped: 3, tall: 3, barrel: 2, serpent: 2, blob: 1 },
    head: { snout: 3, sphere: 2, wide: 3, cube: 1, skull: 1, tall: 1 },
    eyes: { round: 3, glow: 3, ring: 1, slit: 1 },
    mouth: { fangs: 2, grin: 3, maw: 2, flat: 2, tusks: 1 },
    horns: { none: 3, curved: 2, straight: 2, single: 2, ram: 1 },
    ears: { round: 3, long: 2, pointed: 1, none: 1 },
    arms: { long: 3, stubby: 2, claw: 2, none: 1 },
    legs: { long: 3, thick: 2, hoof: 2, stubby: 1, none: 1 },
    wings: { none: 6, feather: 1 },
    tail: { thin: 3, thick: 2, serpent: 1, none: 1, fan: 1 },
    back: { none: 3, mane: 3, spikes: 1 },
    skin: { fur: 3, smooth: 3, scales: 1, stone: 1 },
    hues: [30, 15, 50, 340],
    onsets: ["gr", "imp", "mok", "ad", "tok", "nan", "kish", "ol", "bul", "tik", "san", "aba"],
    nuclei: ["a", "o", "u", "e", "oo", "ai"],
    codas: ["tikoloshe", "mbo", "ndu", "kele", "ogo", "ala", "we", "nga", "ubu", "ro"],
    epithets: ["Baobab-Old", "One-Legged", "Night-Hyena", "Hair-Covered", "Riverbed-Sleeping", "Iron-Toothed", "Drum-Fearing", "Brick-Hidden"],
    domains: ["the Baobab", "the Dry Riverbed", "the Termite Mound", "the Night Fire", "the Iron Forge", "the Red Road"],
    classAdj: ["BAOBAB", "RIVERBED", "NIGHT-FIRE", "IRON", "RED-ROAD", "TERMITE"],
    classNoun: ["TRICKSTER", "STALKER", "SPIRIT", "HYENA-KIN", "BEAST", "WATCHER"],
    habitats: ["inside a baobab hollow that is bigger than the tree", "in a dry riverbed that floods only for it", "behind the forge where the iron cools too fast", "under the bed, if the bed is not raised on bricks"],
    omens: ["when drums are heard from an empty village", "before a river returns without rain", "whenever a hyena laughs with a human voice", "the night the fire burns blue"],
    traits: ["TRICKSTER", "INVISIBLE-WALKER", "RIVERBED-SLEEPER", "TERRITORIAL", "NIGHT-CALLER"],
    archetypes: [
      { name: "TOKOLOSHE", match: { body: ["blob", "hunched"], skin: ["fur"], legs: ["stubby"], arms: ["long"] }, need: 3 },
      { name: "GRootslang", match: { body: ["serpent", "quadruped"], head: ["snout"], mouth: ["tusks"], skin: ["scales"] }, need: 3 },
      { name: "IMPUNDULU", match: { wings: ["feather"], head: ["beak"], legs: ["bird", "long"], eyes: ["glow"] }, need: 3 },
    ],
  },
  malay: {
    id: "malay", label: "Indonesian & Malay Folklore", short: "MALAY",
    body: { tall: 3, floating: 3, hunched: 2, quadruped: 1, blob: 2, serpent: 1 },
    head: { skull: 2, sphere: 2, wide: 3, snout: 2, tall: 2 },
    eyes: { glow: 3, hollow: 2, round: 2, slit: 1 },
    mouth: { fangs: 3, grin: 3, tongue: 3, maw: 1, flat: 1 },
    horns: { none: 5, curved: 1, straight: 1, crown: 1 },
    ears: { long: 2, pointed: 3, round: 1, fin: 1, none: 1 },
    arms: { long: 4, claw: 2, stubby: 1, none: 2 },
    legs: { none: 3, long: 2, stubby: 2, hoof: 1, thick: 1 },
    wings: { none: 5, bat: 2 },
    tail: { none: 3, thin: 2, thick: 1, fan: 1, serpent: 1 },
    back: { none: 4, mane: 3, spikes: 1 },
    skin: { smooth: 4, fur: 2, bone: 1 },
    hues: [0, 120, 40, 270],
    onsets: ["pont", "leyak", "gen", "kunt", "bar", "toy", "ran", "peng", "hant", "jen", "wew", "buto"],
    nuclei: ["a", "i", "u", "e", "ai", "au"],
    codas: ["anak", "gong", "ilan", "tu", "ong", "duk", "ijo", "yang", "lak", "ndi"],
    epithets: ["Banana-Grove", "Long-Haired", "Floating-Headed", "Nail-Fearing", "Frangipani-Scented", "Rice-Stealing", "Giggling-at-Dusk", "Bottle-Bound"],
    domains: ["the Banana Grove", "the Frangipani Tree", "the Rice Barn", "the Night Market", "the Volcano Road", "the Mangrove Coast"],
    classAdj: ["MANGROVE", "BANANA-GROVE", "VOLCANO", "FRANGIPANI", "NIGHT-MARKET", "FLOATING"],
    classNoun: ["HANTU", "SPIRIT", "FIEND", "STALKER", "GRINNER", "WATCHER"],
    habitats: ["in a banana grove that smells of frangipani at midnight", "in a rice barn where the sacks are never lighter", "along the volcano road after the last bus", "between mangrove roots where the tide never leaves"],
    omens: ["when frangipani is smelled without a tree nearby", "the night a baby cries in an empty house", "before a fishing boat returns with no crew", "whenever laughter is heard from the treetops at dusk"],
    traits: ["SHAPESHIFTER", "GROVE-BOUND", "NIGHT-GIGGLER", "SCENT-HERALD", "ILLUSORY"],
    archetypes: [
      { name: "PONTIANAK", match: { body: ["floating", "tall"], legs: ["none"], back: ["mane"], mouth: ["fangs", "tongue"] }, need: 3 },
      { name: "PENANGGAL", match: { body: ["floating"], legs: ["none"], arms: ["none"], head: ["sphere", "skull"] }, need: 3 },
      { name: "BARONG", match: { body: ["quadruped"], back: ["mane"], eyes: ["glow", "round"], mouth: ["fangs", "grin"] }, need: 3 },
      { name: "TOYOL", match: { body: ["blob"], head: ["sphere", "wide"], legs: ["stubby"], arms: ["stubby", "long"] }, need: 3 },
    ],
  },
};

export const MYTHOLOGY_IDS = Object.keys(MYTHOLOGIES) as MythologyId[];

export const UNIVERSAL_TRAITS = [
  "NOCTURNAL", "OMEN-BEARER", "VENOMOUS", "CARRION-EATER", "TERRITORIAL", "CELESTIAL",
  "BURROWER", "MIMIC", "SOUL-EATER", "FOREST-BOUND", "CURSE-BEARER", "RIVER-DWELLER",
  "MOON-CALLED", "SALT-AVERSE", "DREAM-WALKER", "NAME-KNOWER", "SILENT", "EVER-HUNGRY",
  "STORM-FOLLOWER", "WHISPERER", "PATIENT", "ECHOING",
];
